#!/usr/bin/env python

import rospy 
from ros_service.srv import ServiceExample 
from geometry_msgs.msg import Point
# import the code generated by catkin
# we need ServiceExample for the first message type,
# and the ServiceExampleResponse from the second message type from the  ServiceExample.srv file


def turn_on_off(mes):
    if mes.Start.x < 1 and mes.End.y < 2:
        return 'ALI'
    else:
        return 'VELI'


if __name__ == '__main__':
    rospy.init_node('service_respond')

    service = rospy.Service('service_example', ServiceExample, turn_on_off)

    rospy.spin()
